<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "satoshipay"
 *
 * Auto generated by Extension Builder 2016-07-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SatoshiPay',
	'description' => 'Integrates SatoshiPay paid content in TYPO3',
	'category' => 'plugin',
	'author' => 'Christopher Zechendorf',
	'author_email' => 'christopher@zechendorf.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
